### ISSUE TITLE
How to integrate with angular CLI@webpack build tool

### ISSUE THREAD

**Issue by shijumon** [DevExpress/devextreme-angular2#66] opened 2016-08-05 11:08 UTC
Hi,
      I would like to know how to integrate dexextreme-angular2 with angular-cli@webpack project.
thanks,
SHIJU

**Comment by Aden-git** [comment] 2016-08-23 09:20
Hello,
 
It looks like this issue is a duplicate of #47. Let us know if I'm wrong.

**Closed by Aden-git** 2016-08-23 09:20 UTC
Labels: duplicate
