### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular2#104] opened 2016-09-09 13:12 UTC

**Comment by Consi007** [comment] 2016-09-09 13:13
![scheduler](https://cloud.githubusercontent.com/assets/22006033/18387998/647f9ef8-76a8-11e6-922f-8a53a317ff83.png)

**Comment by Consi007** [comment] 2016-09-09 13:14
When i click done, it will error...

**Comment by dxvladislavvolkov** [comment] 2016-09-09 15:41
Hello!
Try setting the "dataSource" option. If this doesn't help, please provide us with an example or project where the problem is reproduced. We need more information to research the issue on our side.

**Comment by dxvladislavvolkov** [comment] 2016-09-27 11:13
I'm closing the issue. Please reopen in case of any questions.

**Closed by dxvladislavvolkov** 2016-09-27 11:13 UTC
Labels: question

**Comment by Consi007** [comment] 2016-09-27 11:37
Ok
