### ISSUE TITLE
Can't edit DxDataGrid if it has a template

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/devextreme-angular2#91] opened 2016-08-26 10:44 UTC
On saving a row, the "template.owner is not a function" error occurs. Use the project from: [https://github.com/GoshaFighten/Bug/tree/master/GridEditing](https://github.com/GoshaFighten/Bug/tree/master/GridEditing).

**Comment by Aden-git** [comment] 2016-08-26 13:15
Hello,

It looks like this issue is a duplicate of #88

**Closed by Aden-git** 2016-08-26 13:15 UTC
Labels: duplicate
