### ISSUE TITLE
DxList height property not working

### ISSUE THREAD

**Issue by pringshia** [DevExpress/devextreme-angular2#95] opened 2016-09-02 17:18 UTC
I ran into an issue today where the `height` property on my DxList component was not working. The issue was occurring on Chrome v52.

This was happening because the DxList element needs to be `display: block` for the height property to work. However, when you create a non-standard HTML element tag (e.g. `<dx-list></dx-list>`), the browser was setting it's display property by default to `inline`. This was preventing the height styles from taking effect.

I was able to override this by manually setting the `display: block` style on the `dx-list` element. Another workaround would be to declare the component as such: `<div dx-list></div>` although this is not encourage per the [style guide](https://angular.io/styleguide#!#05-03).

**Comment by Angelminster** [comment] 2016-09-05 12:03
Maybe similar to #61 ?

**Comment by dxvladislavvolkov** [comment] 2016-09-05 13:23
Yes, you are right. This issue is a duplicate of #61

**Closed** 2016-09-05 13:24 UTC
Labels: duplicate
