### ISSUE TITLE
Dx Accordion- dx template

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular2#99] opened 2016-09-05 13:23 UTC
Dx accordion dont work with dxtemplate

        <dx-accordion dataSource="accordionItems"  [height]="200" [width]="100">
            <div *dxTemplate="let t = data of 'acc'">
                <h1>{{t.CompanyName}}</h1>
            </div>
            <div *dxTemplate="let l = data of 'asd'">
                <div class="accodion-item">
                    <div>
                        <p>
                            <b>{{l.City}}</b>
                            (<span>{{l.State}}</span>)
                        </p>
                        <p>
                            <span>{{l.Zipcode}}</span>
                            <span>{{l.Address}}</span>
                        </p>
                    </div>
                    <div>
                        <p>
                            Phone: <b>{{l.Phone}}</b>
                        </p>
                        <p>
                            Fax: <b>{{l.Fax}}</b>
                        </p>
                        <p>
                            Website:
                        </p>
                    </div>
                </div>
            </div>
        </dx-accordion>

**Comment by dxvladislavvolkov** [comment] 2016-09-05 14:37
It looks like this issue is a duplicate of #98

**Closed** 2016-09-05 14:38 UTC
Labels: duplicate
