### ISSUE TITLE
Cell Customization of DataGrid in Angular 2

### ISSUE THREAD

**Issue by 14Muhammad** [DevExpress/devextreme-angular2#42] opened 2016-07-13 19:04 UTC
Hello,
How we can achieve cell customization in Angular 2 as given for angular 1 in link below:
http://js.devexpress.com/Demos/WidgetsGallery/#demo/data_grid-templates-cell_customization/angular
Kindly provide some demo/example for angular2 cell customization in dataGrid.

Regards, 
Ali

**Comment by dxbykov** [comment] 2016-07-14 15:05
Hello Muhammad,

If I understand you right, you'd like to use the 'onCellPrepared' event to customize dxDataGrid cells. I've just checked it and confirm that this event is not raised. It seems to be a duplicate of #14. We'll check it once it's fixed.

To subscribe to this event, you can use Angular 2 event bindings:

```html
  <dx-data-grid (onCellPrepared)="onCellPrepared" ...></dx-data-grid>
```

and declare a handler in your TS file:

```js
  onCellPrepared(e) {
    ...
  }
```

**Comment by staran** [comment] 2016-07-20 10:46
Hi, I'm currently trying to subscribe to the onRowClick event of the dx-data-grid, the event fires but I don't get an event object (which I need to dig out some row-data), this is what I use:

`<dx-data-grid ... (onRowClick)="taskGridRowClicked()" ...></dx-data-grid>`

and in my ts file:

```
taskGridRowClicked(e) {
  ...
}
```

What am i getting wrong here?
Thanks.

Regards
Andreas

**Comment by dxbykov** [comment] 2016-07-20 11:26
You need to use the $event value as follows:

```html
<dx-data-grid ... (onRowClick)="taskGridRowClicked($event)" ...></dx-data-grid>
```

**Comment by dxbykov** [comment] 2016-07-28 15:55
Duplicate of #14

**Closed by dxbykov** 2016-07-28 15:55 UTC
Labels: bug, duplicate
